name: Snyk Vulnerability Check and Issue Creation

on:
  push:
    branches:
      - main

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: npm install

      - name: Snyk Test
        id: snyk_test
        uses: snyk/actions@v2
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test

      - name: Create GitHub Issue for Vulnerabilities
        if: ${{ steps.snyk_test.outputs.snyk-severity-high != '' || steps.snyk_test.outputs.snyk-severity-medium != '' }}
        uses: peter-evans/create-issue@v3
        with:
          title: 'Snyk Vulnerabilities Detected in Project'
          body: |
            The following vulnerabilities were found in the repository:
            - Severity: High/Medium
            - Description: [Detailed vulnerability list]
            - Link to full report: [Snyk Report Link]
          labels: 'vulnerability'
          assignees: 'your-github-username'
